---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-cluster-example
  labels:
    app: akka-cluster-example
    prometheus.io/scrape: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akka-cluster-example
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: akka-cluster-example
        actorSystemName: akka-cluster-example
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: akka-cluster-example
        image: akka-cluster-example:0.1.0
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
        env:
        - name: REQUIRED_CONTACT_POINT_NR
          value: "3"
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
        ports:
        - name: remoting
          containerPort: 2552
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 8558
        - name: metrics
          containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: akka-cluster-example-svc
  annotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/scheme": http
    "prometheus.io/path": "/metrics"
    "prometheus.io/port": "9091"
spec:
  type: NodePort
  selector:
    app: akka-cluster-example
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9091
    targetPort: 9091
